### ISSUE TITLE
Python manage.py migrate

### ISSUE THREAD

**Issue by cubanboo** [dereklh4/classact#49]
## Description
Syntax error:   

File "manage.py", line 14
    ) from exc
         ^
SyntaxError: invalid syntax

## Severity
Medium, program can’t run at all but may be different for different users

## Comments
Similar to above, if python2 and 3 are on your computer, you need to specify “python3 manage.py migrate.”

Using a virtual environment would help a lot, as you can pip install all the requirements in the virtual environment so that it can run the same on any computer.

**Comment by dereklh4** [comment]
Python 3 is listed as a dependency of the backend in the project, so not an issue and we'll leave as is.
