### ISSUE TITLE
 Pip install -r requirements.txt

### ISSUE THREAD

**Issue by Pallasite** [dereklh4/classact#50]
## Description
If python2 and 3 are on your computer, you need to specify “Pip3 install -r requirements.txt” rather than “pip install -r requirements.txt” Otherwise, Django==2.1.2 won’t be able to be installed.

Running the backend on a virtual environment would be very beneficial, so anyone’s computer can run the program without conflict.

## Severity
Medium

**Comment by dereklh4** [comment]
Included a note in the readme. The requirements file doesn't stop anyone to run a virtual environment on their computer to install the dependencies. That's actually how most of us do it.
